name: IntelliJ Plugin Compatibility

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [ main ]

  # Trigger the workflow on any pull request
  pull_request:

  # Trigger the workflow on a schedule; daily
  schedule:
    - cron: '0 0 * * *'

jobs:
  compatibility:
    name: Ensure plugin compatibility against targeted platform version & the latest EAP snapshot for both IDEA Community, IDEA Ultimate.

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.4.0

      - name: Setup Java 11
        uses: actions/setup-java@2c7a4878f5d120bd643426d54ae1209b29cc01a3 # v2
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Build the plugin
        run: ./gradlew buildPlugin

      - name: Verify plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
        with:
          ide-versions: |
            ideaIC:2022.1
            ideaIU:2022.1
            ideaIC:LATEST-EAP-SNAPSHOT
            ideaIU:LATEST-EAP-SNAPSHOT

      - name: Get log file path and print contents
        run: |
          echo "The log file path is: ${{steps.verify.outputs.verification-output-log-filename}}" ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}
